# Generated by Django 4.0.3 on 2022-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesetion_text',
            new_name='question_text',
        ),
    ]
